### ISSUE TITLE
Does the grid view support Images? seems the images expand when i return an image as child

### ISSUE THREAD

**Issue by Chepond** [baoolong/DragableGridview#1]
class AdCard extends StatefulWidget {
  AdCard(this.ad);

  final Pic ad;

  _AdCardState createState() => _AdCardState(ad);
}

class _AdCardState extends State<AdCard> {
  //to keep things readable
  Pic _ad;
  _AdCardState(this._ad);

  void initState() {
    super.initState();

    getImage().then((val) => setState((){
      _ad.image = val;
      _image = val;
    }));

  }

  Image _image = Image.asset('assets/images/loading.gif');

  Future<Image> getImage() async {
    if (_ad.image != null) {
      return _ad.image;
    } else {
      return Image.memory(await http.readBytes(_ad.imageUrl));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      semanticContainer: false,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          _image,
        ],
      ),
    );
  }
}

class Pic {
  final String imageUrl;
  Image image;

  Pic(this.imageUrl);

  Pic.fromJson(Map<String, dynamic> json)
      : imageUrl = json['imageUrl'];

  Map<String, dynamic> toJson() =>
      {
        'imageUrl': imageUrl
      };
}

class DragAbleGridViewDemo extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return new DragAbleGridViewDemoState();
  }

}

class ItemBin extends DragAbleGridViewBin{

  ItemBin( this.adCard);

  String data;
  AdCard adCard;

  @override
  String toString() {
    return 'ItemBin{data: $data, dragPointX: $dragPointX, dragPointY: $dragPointY, lastTimePositionX: $lastTimePositionX, lastTimePositionY: $lastTimePositionY, containerKey: $containerKey, containerKeyChild: $containerKeyChild, isLongPress: $isLongPress, dragAble: $dragAble}';
  }

}
class DragAbleGridViewDemoState extends State<DragAbleGridViewDemo>{

  List<ItemBin> itemBins=new List();
  String actionTxtEdit="编辑";
  String actionTxtComplete="完成";
  String actionTxt;
  var editSwitchController=EditSwitchController();
  bool _isLoaded = false;

  Future<List<Pic>> fetchPics() async {
    //the link you want to data from, goes inside get
    final response = await http
        .get('https://blasanka.github.io/watch-ads/lib/data/ads.json');

    if (response.statusCode == 200) {
      var abcd = json.decode(response.body);
      final List parsedList = json.decode(response
          .body); //assuming this json returns an array of signupresponse objects

      List<Pic> list = parsedList.map((val) => Pic.fromJson(val)).toList();

      return list;
    }
    return [];
  }

  @override
  void initState() {
    super.initState();
    actionTxt=actionTxtEdit;
    fetchPics().then((val) => setState(() {
      val.forEach((pic){
        itemBins.add(ItemBin(AdCard(pic)));
      });
      _isLoaded = true;
    }));
  }

  @override
  Widget build(BuildContext context) {
    if(_isLoaded) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text("可拖拽GridView"),
          actions: <Widget>[
            new Center(
                child: new GestureDetector(
                  child: new Container(
                    child: new Text(
                      actionTxt, style: TextStyle(fontSize: 19.0),),
                    margin: EdgeInsets.only(right: 12),
                  ),
                  onTap: () {
                    changeActionState();
                    editSwitchController.editStateChanged();
                  },
                )
            )
          ],
        ),
        body: new DragAbleGridView(
//          decoration: new BoxDecoration(
//            borderRadius: BorderRadius.all(new Radius.circular(3.0)),
//            border: new Border.all(color: Colors.blue),
//          ),
          mainAxisSpacing: 10.0,
          crossAxisSpacing: 10.0,
          crossAxisCount: 2,
          deleteIconName: "assets/images/icon_cancel.png",
          deleteIconMarginTopAndRight: 6.0,
          itemPadding: EdgeInsets.fromLTRB(8.0, 5.0, 8.0, 5.0),
        childAspectRatio:1.8,
          itemBins: itemBins,
          editSwitchController: editSwitchController,
          child: (int position) {
            return itemBins[position].adCard;
          },
          editChangeListener: () {
            changeActionState();
          },
        ),
      );
    }else {
      return Center(
          child:
          new CircularProgressIndicator());
    }
  }

  void changeActionState(){
    if(actionTxt==actionTxtEdit){
      setState(() {
        actionTxt=actionTxtComplete;
      });
    }else{
      setState(() {
        actionTxt=actionTxtEdit;
      });
    }
  }
}

**Comment by Chepond** [comment]
when I set crossAxisCount :1 in DragAbleGridView, it works fine, but obviously can't drag cuz the images are too big.
Also can it made to scroll when the drag item hits the edge of the DragAbleGridView(top or bottom for vertical, left or right for horizontal)
Many thanks

**Comment by Chepond** [comment]
Will I be able to set long press duration to trigger the drag?
Will I be able to set the duration for the gridview to refresh the itself when the dragItem is dragged to a certain position?

**Comment by Chepond** [comment]
> when I set crossAxisCount :1 in DragAbleGridView, it works fine, but obviously can't drag cuz the images are too big.
> Also can it made to scroll when the drag item hits the edge of the DragAbleGridView(top or bottom for vertical, left or right for horizontal)
> Many thanks

I have solved this out by adding below bolded code
@override
  Widget build(BuildContext context) {

      **var size = MediaQuery.of(context).size;
      var width = size.width;
      width = (width - ((crossAxisCount-1)*crossAxisSpacing) - (mainAxisSpacing*2))/crossAxisCount;**
      
      return DragAbleGridView(
           child: (int position) {
            var item = myItem;
            return Container(
                 child: item,
                width: **stat**,
                height: **width**,
            );
        },
);
}

**Comment by baoolong** [comment]
no parameters to set the duration of the long press; 
no parameter to set the duration of the animation；
but，You can copy my code to your project to set it；
and Add code that triggers scrolling when dragged to the edge

    @override
      void initState() {   
        super.initState();   
        // you can set animation duration  at here
        controller = new AnimationController(duration: const Duration(milliseconds: 300), vsync: this);
    }
 -------------------------------------------------------------------------------------------
      ///you can set long press duration  at here
      void _handLongPress(int index) async{
        await Future.delayed(new Duration(milliseconds: 800));
      }

**Comment by baoolong** [comment]
i have push  ,  you can download the newest code

**Comment by Chepond** [comment]
Thanks so much bro, I’m actually new to flutter haha thanks for helping
Anyways what should I do if I wanna disable the draggable feature by long press

**Comment by baoolong** [comment]
Do you just need the delete animation?

**Comment by Chepond** [comment]
可以直接關掉那個Long press draggable的function？這讓它behave as正常的gridview
因為我想讓只有權力的用家才能edit
但不只那個右上角能進人edit mode
長按也會~

**Comment by Chepond** [comment]
> no parameters to set the duration of the long press;
> no parameter to set the duration of the animation；
> but，You can copy my code to your project to set it；
> and Add code that triggers scrolling when dragged to the edge
> 
> ```
> @override
>   void initState() {   
>     super.initState();   
>     // you can set animation duration  at here
>     controller = new AnimationController(duration: const Duration(milliseconds: 300), vsync: this);
> }
> ```
> ```
>   ///you can set long press duration  at here
>   void _handLongPress(int index) async{
>     await Future.delayed(new Duration(milliseconds: 800));
>   }
> ```

sorry about that, I actually dunno where to put these code, can u include them in the example? many thanks

**Comment by baoolong** [comment]
Tell me your email, I am modifying the code and sending it to you.

**Comment by Chepond** [comment]
yamchepond@gmail.com

**Comment by Chepond** [comment]
I’m sorry the email has typo
It’s yamchepond2@gmail.com

**Comment by baoolong** [comment]
after go home,i will send to you agein

**Comment by Chepond** [comment]
Thank you so much, looking forward to ur masterpiece!! Many thanks
