### ISSUE TITLE
Shaking effect

### ISSUE THREAD

**Issue by fvisticot** [baoolong/DragableGridview#2]
Great library.
Is it currently possible to allow a "shaking" effect as the iPhone dashboard screen ?
My objetive is to use your library to mimic iPhone screen.

**Comment by baoolong** [comment]
I can do it,tell me your email , I will give my code when I complete

**Comment by fvisticot** [comment]
Hello,
For me the best solution would be to provide an extra sample with this « shaking » sample.
But if you want I can give you my private email

Fred

**Comment by fvisticot** [comment]
Any news on this point ? Your work is really good and I seems you need to develop the plugin for more adoption

**Comment by baoolong** [comment]
Sorry, I am replying to you so late. I recently changed my job. I am very busy at work. I have almost no time. You can change the code yourself. This is not difficult.
