### ISSUE TITLE
Setting tile size generates Overlaping

### ISSUE THREAD

**Issue by fvisticot** [baoolong/DragableGridview#4]
I try to set a width/height for the draggable tiles (to make it a 100x100 square tile) and the result is that all is overlapped.
I was assuming tiles will keep padding and no overlap

**Comment by Mrjen** [comment]
@fvisticot me too

**Comment by baoolong** [comment]
I used OverflowBox in the plugin, so there will be overflow. If there is a horizontal overflow, please reset the width of the children. If it is vertical overflow, please set childAspectRatio to control the aspect ratio of child. Only childAspectRatio can be set to control the height of children.
