### ISSUE TITLE
ItemBin's list state changed won't trigger GridView update.

### ISSUE THREAD

**Issue by AlexV525** [baoolong/DragableGridview#6]
Hi there!
When this plugin migrate with images choosing, it seems that then `List<ItemBin>` updated, the GridView didn't update, which cause `_initItemPositions` won't triggered. And drag item would failed because positions didn't update.
Hope this can be solve~

作者你好~
这个插件在图片选择应用中，当ItemBin的List被更新时，GridView没有被更新，导致`_initItemPositions`没有被触发，List的索引没有更新到数据中，此时拖动会造成数组越界（因为原数组为空）。
希望这个问题可以解决~

**Comment by baoolong** [comment]
Try using the new version

**Comment by AlexV525** [comment]
> Try using the new version

Thanks, I fix this by adding `itemBinUpdated` to controller, but I'll try the new version to see if the problem has been solved.

Code below:
```
class EditSwitchController{
  DragAbleGridViewState dragAbleGridViewState;

  void editStateChanged(){
    dragAbleGridViewState.changeDeleteIconState();
  }

  void itemBinUpdated () {
    dragAbleGridViewState._initItemPositions();
  }
}
```

**Comment by AlexV525** [comment]
Verified. Thanks a lot 😄

**Comment by baoolong** [comment]
New version has better performance
