### ISSUE TITLE
deleteIcon can be a Widget instead of Image.

### ISSUE THREAD

**Issue by AlexV525** [baoolong/DragableGridview#7]
`deleteIcon` can be a widget which makes user can customize with icon or other widget, but not only Image.
`final Image deleteIcon` -> `final Widget deleteIcon`

**Comment by baoolong** [comment]
I will update this feature when I am free.Or you fork the project and change it yourself.

**Comment by AlexV525** [comment]
I changed this myself already, but this can be an enhancement for next version.
